Repository civicrm/org.civicrm.shoreditch, pull requests merged in 2021-03, with the labels that each got.

#492 CPS-480: Fix broken buttons
  scss/bootstrap/overrides/crm/_button.scss
  scss/civicrm/common/_buttons.scss
Labels: bug

#496 MAE-493: Style the form buttons and Direct Debit batch form actions
  scss/civicrm/common/_buttons.scss
Labels: bug

#500 CPS-515: Fix Dashlet styles
  scss/civicrm/dashboard/_dashboard.scss
  scss/civicrm/dashboard/dashlets/_activity-selector.scss
  scss/civicrm/dashboard/dashlets/_reports.scss
Labels: bug, regression

#499 CPS-481: Fix Button border
  scss/bootstrap/overrides/crm/_button.scss
Labels: bug, regression

#501 CPS-521: v1.0.0-beta.5 Release
  README.md
  css/bootstrap.css
  css/custom-civicrm.css
  info.xml
Labels: release
